// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Command = { "type": "Join", name: string, } | { "type": "Buzz" } | { "type": "Answer", text: string, } | { "type": "ExtendTimer", delta_secs: number, };
