// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Grant } from "./Grants";

export type ClientMessage = { "kind": "Join", name: string, } | { "kind": "Reconnect", token: string, } | { "kind": "Authed", token: string, cmd: Command, };

export type ClientView = { players: { [key in string]: Array<Grant> }, };

export type Command = { "kind": "Kick", player: string, } | { "kind": "Buzz" } | { "kind": "Answer", text: string, } | { "kind": "ExtendTimer", delta_secs: number, };

export type ServerMessage = { "kind": "Joined", token: string, } | { "kind": "Snapshot" } & ClientView | { "kind": "Error", message: string, };
