// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClientView } from "./ClientView";
import type { Notification } from "./Notification";

export type ServerMessage = { "kind": "Joined", token: string, } | { "kind": "Snapshot" } & ClientView | { "kind": "Notify" } & Notification | { "kind": "Error", message: string, };
